name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CodeFormattingCheck:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Mint packages
        id: mint-cache
        uses: actions/cache@v3
        with:
          path: /usr/local/lib/mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-
      - name: Install Mint
        run: |
          brew upgrade mint || brew install mint || true
      - name: Install swiftformat via mint
        if: steps.mint-cache.outputs.cache-hit != 'true'
        run: mint bootstrap
      - name: Format Swift code
        run: |
          mint swiftformat --version
          mint swiftformat . --config .swiftformat --lint
      - name: Lint Swift code
        run: |
          mint swiftlint --version
          mint swiftlint lint --strict --config .swiftlint.yml --quiet
