name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Install mint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.7"]
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Get swift version
        run: swift --version
      - name: Cache Mint
        id: cache-mint
        uses: actions/cache@v3
        with:
          path: ~/mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-
      - uses: actions/checkout@v2
      - name: Install linters
        env:
          MINT_PATH: "~/mint"
        run: |
          git clone https://github.com/yonaskolb/Mint.git
          cd Mint
          swift run mint install yonaskolb/mint
          mint bootstrap // Installs all the packages in your Mintfile, by default, without linking them globally

      - name: Run linters
        run: |
          swiftlint --version
          swiftlint lint --strict --config .swiftlint.yml --quiet
          swiftformat --version
          swiftformat . --config .swiftformat --lint
