name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Install mint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.7"]
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Get swift version
        run: swift --version
      - name: Cache Mint
        if: ${{ matrix.os == 'macos-latest' }}
        id: cache-mint
        uses: actions/cache@v3
        with:
          path: ~/mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-
      - uses: actions/checkout@v2
      - name: Install Dependencies (Mac only)
        if: ${{ matrix.os == 'macos-latest' && steps.cache-npm.outputs.cache-hit != 'true' }}
        env:
          MINT_PATH: "~/mint"
        run: |
          brew install mint
          mint bootstrap
